name: Build and Release  # name it whatever you like
on:
  workflow_dispatch:

permissions: # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-defindex-distributor:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}          # use git tag as unique release name
      package: 'defindex-distributor'                # package name to build
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}    # don't modify this line
